# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Udl < Formula
  desc "Single Go binary replacing Sonarr + Radarr + NZBGet for Usenet-based media automation"
  homepage "https://github.com/jokull/udl"
  version "0.2.2"
  license "MIT"

  depends_on "par2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jokull/udl/releases/download/v0.2.2/udl_0.2.2_darwin_amd64.tar.gz"
      sha256 "70845f8ae468d339a5d002d6f46ab537f0da36a30fd11fcadadddfc451196c74"

      define_method(:install) do
        bin.install "udl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jokull/udl/releases/download/v0.2.2/udl_0.2.2_darwin_arm64.tar.gz"
      sha256 "a13db6ae936406dcb6bb552d1db2a8a0a4a47b0e9cd5fb9e0c4524335ab813d6"

      define_method(:install) do
        bin.install "udl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jokull/udl/releases/download/v0.2.2/udl_0.2.2_linux_amd64.tar.gz"
      sha256 "1d9b0c0af896e406ed20ab988e322a5d79052cf17e71214c45356aec2c393ea0"
      define_method(:install) do
        bin.install "udl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jokull/udl/releases/download/v0.2.2/udl_0.2.2_linux_arm64.tar.gz"
      sha256 "84c517fdf4a87070266f859149eb2acfef129b74566b96bddfb899697045be41"
      define_method(:install) do
        bin.install "udl"
      end
    end
  end

  test do
    system "#{bin}/udl", "--help"
  end
end
